name: Angular CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install Angular
        run: npm install -g @angular/cli
        
      - name: Install NPM Dependencies
        run: npm install
        
      - name: Build
        run: ng build
        
      - name: Zip files
        run: zip -r my_project.zip .
        
      - name: Create Uploads Directory
        run: mkdir uploads && mv my_project.zip uploads/
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./uploads/
          
      - name: SSH and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd apis.lk/nifraz/main/
            unzip -o my_project.zip
